feeds:
  - https://brandur.org/articles.atom
  - https://michael-mckenna.com/blog/atom.xml
  - https://waitbutwhy.com/feed
  - http://www.joelonsoftware.com/rss.xml
  - https://benhoyt.com/writings/rss.xml
  - https://jvns.ca/atom.xml
time_zone: Pacific/Auckland
