name: Generate Digest

on:
    workflow_dispatch:
    schedule:
        - cron: '5 13 * * *'

jobs:
  build:
    name: Generate daily digest
    runs-on: ubuntu-latest
    steps:

    - name: 📄 Checkout
      uses: actions/checkout@v3

    - name: 🛠️ Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: 🚀 Run md process
      run: | 
        cd RssToMd 
        dotnet run --configuration Release --destination ../Web/content/digest

    - name: 💾 Check in changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'myquay@users.noreply.github.com'
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}
        git add */digest/*
        git commit -m "Daily Digest"
        git push