name: Generate Digest

on:
    workflow_dispatch:
    schedule:
        - cron: '5 13 * * *'
# Allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Generate daily digest
    runs-on: ubuntu-latest
    steps:

    - name: 📄 Checkout
      uses: actions/checkout@v3

    - name: 🛠️ Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: 🚀 Run md process
      run: | 
        cd RssToMd 
        dotnet run --configuration Release --destination ../Web/content/digest

    - name: 💾 Check in changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'myquay@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}
        git add */digest/*
        git commit -m "Daily Digest"
        git push

  deploy:
    needs: build
    name: Deploy daily digest changes
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 💾 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true #Themes in Hugo are usually submodules

      - name: 📄 Setup Pages
        uses: actions/configure-pages@v3

      - name: ✨ Setup Hugo
        env:
          HUGO_VERSION: 0.111.3
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: ✍️ Set outputs
        id: custom_outputs
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: 🛠️ Build website
        run: hugo -s ${{github.workspace}}/Web -d ${{github.workspace}}/dist --environment github-pages --log -v
        
      - name: 📦 Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '${{github.workspace}}/dist'
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2